import { ArrowRight, LogOut, Plus, Smartphone } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { getMe, getMerchantPayments } from '../api/merchants';
import { MerchantStats } from '../components/MerchantStats';
import { PaymentStatusBadge } from '../components/PaymentStatusBadge';
import { supabase } from '../config/supabase';
import type { Merchant, Payment } from '../types';
import { money, relativeDate, short } from '../utils';

export function MerchantDashboard() {
  const navigate = useNavigate(); const [payments, setPayments] = useState<Payment[]>([]), [merchant, setMerchant] = useState<Merchant>(), [error, setError] = useState('');
  useEffect(() => { let active = true; const load = async () => { try { const [me, rows] = await Promise.all([getMe(), getMerchantPayments()]); if (active) { setMerchant(me.merchant); setPayments(rows); } } catch (e) { if (active) setError(e instanceof Error ? e.message : 'Unable to load dashboard'); } }; void load(); const timer = setInterval(load, 5000); return () => { active = false; clearInterval(timer); }; }, []);
  const completed = payments.filter((payment) => payment.status === 'COMPLETED'), total = completed.reduce((sum, payment) => sum + payment.amountGhs, 0);
  return <div className="shell py-10"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Merchant dashboard</p><h1 className="mt-2 text-3xl font-extrabold">{merchant?.name || 'Your store'}</h1><p className="mt-2 flex items-center gap-2 text-sm text-[#63736b]"><Smartphone size={16} />MTN · {merchant?.phone || 'Loading…'}</p></div><div className="flex gap-3"><button className="btn-secondary" onClick={async () => { await supabase.auth.signOut(); navigate('/merchant/login'); }}><LogOut size={17} />Sign out</button><Link to="/merchant/create-invoice" className="btn-primary"><Plus size={18} />Create invoice</Link></div></div>{error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<MerchantStats total={total} count={completed.length} /><div className="card mt-6 overflow-hidden"><div className="flex items-center justify-between p-6"><div><h2 className="text-xl font-extrabold">Recent payments</h2><p className="mt-1 text-sm text-[#66766e]">Verified Sepolia and Mobile Money activity</p></div><ArrowRight className="text-emerald" /></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#f6f8f5] text-xs uppercase tracking-wider text-[#6d7c74]"><tr>{['Reference','Amount','Crypto paid','Customer','Blockchain','MoMo payout','Date'].map((heading) => <th key={heading} className="px-6 py-3 font-bold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-black/5">{payments.map((payment) => <tr key={payment.transactionId}><td className="px-6 py-4 font-bold"><Link to={`/transaction/${payment.transactionId}`}>{payment.invoiceId}</Link></td><td className="px-6 py-4 font-bold">{money(payment.amountGhs)}</td><td className="px-6 py-4 text-sm">{payment.amountCrypto} {payment.token}</td><td className="px-6 py-4 text-sm">{short(payment.customerWallet)}</td><td className="px-6 py-4 text-xs font-bold text-emerald">{payment.blockchainStatus}</td><td className="px-6 py-4"><PaymentStatusBadge status={payment.status} /></td><td className="px-6 py-4 text-sm">{relativeDate(payment.createdAt)}</td></tr>)}</tbody></table>{!payments.length && <p className="p-8 text-center text-sm text-[#66766e]">No payments yet. Create an invoice to begin.</p>}</div></div></div>;
}
