import {AlertTriangle,ArrowLeft,LockKeyhole,Store} from 'lucide-react';
import {useEffect,useState} from 'react';import {Link,useNavigate,useParams} from 'react-router-dom';
import {erc20Abi,parseEther,parseUnits,zeroAddress} from 'viem';import {useAccount,usePublicClient,useWalletClient} from 'wagmi';
import {getInvoice} from '../api/invoices';import {confirmPayment,preparePayment} from '../api/payments';
import {ConnectWalletButton} from '../components/ConnectWalletButton';import {ErrorState,LoadingState} from '../components/States';import {PaymentSummaryCard} from '../components/PaymentSummaryCard';import {TokenSelector} from '../components/TokenSelector';
import {chainId,isMockMode,usdcAddress} from '../config/blockchain';import {mockStore} from '../mocks/store';import type {Invoice,Payment,SupportedToken} from '../types';import {maskPhone,money,networkName} from '../utils';

const walletError=(error:unknown)=>{const message=error instanceof Error?error.message:'';if(/rejected|denied/i.test(message))return 'Payment was rejected in your wallet. No funds were sent.';if(/insufficient/i.test(message))return 'Your wallet does not have enough balance for this payment and network fee.';if(/chain|network/i.test(message))return 'Please switch your wallet to Ethereum Sepolia and try again.';return 'The blockchain transaction failed. No Mobile Money payout was started.'};

export function PaymentPage(){
  const {invoiceId}=useParams(),nav=useNavigate(),{address,isConnected,chain}=useAccount(),{data:wallet}=useWalletClient(),publicClient=usePublicClient();
  const [invoice,setInvoice]=useState<Invoice>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[token,setToken]=useState<SupportedToken>('ETH'),[submitting,setSubmitting]=useState(false),[walletState,setWalletState]=useState('');
  const load=()=>{setLoading(true);setError('');getInvoice(invoiceId||'').then(setInvoice).catch(e=>setError(e instanceof Error?e.message:'Invoice unavailable')).finally(()=>setLoading(false))};useEffect(load,[invoiceId]);
  if(loading)return <div className="shell py-12"><LoadingState label="Fetching secure invoice…"/></div>;if(error&&!invoice)return <div className="shell py-12"><ErrorState message={error} onRetry={load}/></div>;if(!invoice)return <div className="shell py-12"><ErrorState message="This invoice is invalid."/></div>;
  const expired=new Date(invoice.expiresAt)<new Date(),paid=invoice.status==='COMPLETED',wrongNetwork=isConnected&&chain?.id!==chainId;
  const confirm=async()=>{if(expired||paid||submitting)return;setSubmitting(true);setError('');
    try{const prepared=await preparePayment(invoice,token);const payment:Payment={transactionId:prepared.transactionId,invoiceId:invoice.id,status:'BLOCKCHAIN_CONFIRMING',blockchainStatus:'CONFIRMING',payoutStatus:'PENDING',amountCrypto:prepared.amountCrypto,token,amountGhs:invoice.amountGhs,customerWallet:address||'0xDemo9E45b8847d8322A5fA52A5f4D9C9b2a8',createdAt:new Date().toISOString(),merchantName:invoice.merchantName};
      if(isMockMode){mockStore.savePayment(payment);nav(`/transaction/${prepared.transactionId}`);return}
      if(!wallet||!publicClient||!address)throw new Error('Wallet is not connected');if(chain?.id!==chainId)throw new Error('Wrong network');if(prepared.recipientAddress===zeroAddress)throw new Error('Payment recipient is not configured');if(token==='USDC'&&usdcAddress===zeroAddress)throw new Error('USDC token is not configured');
      setWalletState('Awaiting wallet approval');
      const txHash=token==='ETH'
        ?await wallet.sendTransaction({account:address,chain,value:parseEther(prepared.amountCrypto),to:prepared.recipientAddress})
        :await wallet.writeContract({account:address,chain,address:usdcAddress,abi:erc20Abi,functionName:'transfer',args:[prepared.recipientAddress,parseUnits(prepared.amountCrypto,6)]});
      setWalletState('Transaction submitted · confirming on Sepolia');
      const receipt=await publicClient.waitForTransactionReceipt({hash:txHash,confirmations:1});if(receipt.status!=='success')throw new Error('Transaction reverted');
      setWalletState('Transaction confirmed');await confirmPayment(prepared.transactionId,txHash);nav(`/transaction/${prepared.transactionId}`);
    }catch(e){setError(walletError(e));setSubmitting(false);setWalletState('')}
  };
  return <div className="shell py-8"><Link to="/pay" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-forest"><ArrowLeft size={17}/>Choose another invoice</Link><div className="mx-auto grid max-w-5xl gap-6 lg:grid-cols-[1fr_.8fr]"><div className="space-y-5"><div className="card p-6 sm:p-8"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-forest text-white"><Store/></span><span className="rounded-full bg-emerald/10 px-3 py-1 text-xs font-bold text-emerald">Secure invoice</span></div><p className="mt-7 text-sm text-[#66766e]">Paying</p><h1 className="mt-1 text-3xl font-extrabold">{invoice.merchantName}</h1><p className="mt-2 text-[#66766e]">{invoice.description}</p><div className="my-6 border-t border-black/5"/><p className="text-sm text-[#66766e]">Amount requested</p><p className="amount mt-1 text-4xl font-extrabold text-forest">{money(invoice.amountGhs)}</p><p className="mt-5 rounded-2xl bg-[#e9f5ed] p-4 text-sm font-semibold leading-6 text-forest">{invoice.merchantName} will receive {money(invoice.amountGhs)} directly through {networkName(invoice.network)}.</p><div className="mt-4 flex justify-between text-xs text-[#718078]"><span>Expires {new Date(invoice.expiresAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span>{maskPhone(invoice.merchantPhone)}</span></div></div><div className="card p-6"><label className="label">Choose how to pay</label><TokenSelector value={token} onChange={setToken}/></div></div>
  <div className="space-y-5"><PaymentSummaryCard invoice={invoice} token={token}/><div className="card p-6"><ConnectWalletButton/>{isMockMode&&!isConnected&&<p className="mt-3 text-center text-xs text-[#68776f]">No wallet installed? The demo payment can still continue securely.</p>}<button onClick={confirm} disabled={expired||paid||submitting||wrongNetwork||(!isConnected&&!isMockMode)} className="btn-primary mt-3 w-full">{walletState|| (submitting?'Preparing transaction…':expired?'Invoice expired':paid?'Already paid':'Confirm payment')}</button><p className="mt-4 flex items-center justify-center gap-1.5 text-center text-xs text-[#75837c]"><LockKeyhole size={13}/>SikaPay never takes custody of your wallet.</p>{error&&<p className="mt-3 flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={17}/>{error}</p>}</div></div></div></div>;
}
