import { AlertTriangle, ArrowLeft, LockKeyhole, Store } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { erc20Abi, parseEther, parseUnits, zeroAddress } from 'viem';
import { useAccount, usePublicClient, useWalletClient } from 'wagmi';
import { getInvoice } from '../api/invoices';
import { confirmPayment, preparePayment } from '../api/payments';
import { ConnectWalletButton } from '../components/ConnectWalletButton';
import { ErrorState, LoadingState } from '../components/States';
import { PaymentSummaryCard } from '../components/PaymentSummaryCard';
import { TokenSelector } from '../components/TokenSelector';
import { chainId, contractAddress, usdcAddress } from '../config/blockchain';
import type { Invoice, SupportedToken } from '../types';
import { maskPhone, money, networkName } from '../utils';

const sikaPayAbi = [{ type: 'function', name: 'payInvoice', stateMutability: 'payable', inputs: [{ name: 'invoiceId', type: 'bytes32' }, { name: 'token', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] }] as const;
const walletError = (error: unknown) => { const message = error instanceof Error ? error.message : ''; if (/rejected|denied/i.test(message)) return 'Payment was rejected in your wallet.'; if (/insufficient/i.test(message)) return 'Your wallet does not have enough funds.'; if (/chain|network/i.test(message)) return 'Please switch your wallet to Ethereum Sepolia.'; return message || 'The blockchain transaction failed.'; };

export function PaymentPage() {
  const { invoiceId } = useParams(), navigate = useNavigate(); const { address, isConnected, chain } = useAccount(); const { data: wallet } = useWalletClient(); const publicClient = usePublicClient();
  const [invoice, setInvoice] = useState<Invoice>(), [loading, setLoading] = useState(true), [error, setError] = useState(''), [token, setToken] = useState<SupportedToken>('ETH'), [submitting, setSubmitting] = useState(false), [walletState, setWalletState] = useState('');
  const load = () => { setLoading(true); getInvoice(invoiceId || '').then(setInvoice).catch((e) => setError(e instanceof Error ? e.message : 'Invoice unavailable')).finally(() => setLoading(false)); }; useEffect(load, [invoiceId]);
  if (loading) return <div className="shell py-12"><LoadingState label="Fetching secure invoice…" /></div>; if (error && !invoice) return <div className="shell py-12"><ErrorState message={error} onRetry={load} /></div>; if (!invoice) return <div className="shell py-12"><ErrorState message="This invoice is invalid." /></div>;
  const expired = new Date(invoice.expiresAt) < new Date(), paid = invoice.status === 'COMPLETED', wrongNetwork = isConnected && chain?.id !== chainId;
  const pay = async () => { if (!wallet || !publicClient || !address || expired || paid) return; setSubmitting(true); setError(''); try { if (chain?.id !== chainId) throw new Error('Wrong network'); if (contractAddress === zeroAddress) throw new Error('SikaPay contract is not configured'); const quote = await preparePayment(invoice, token); const amount = token === 'ETH' ? parseEther(quote.amountCrypto) : parseUnits(quote.amountCrypto, 6);
      if (token === 'USDC') { if (usdcAddress === zeroAddress) throw new Error('USDC is not configured'); setWalletState('Approve USDC in your wallet'); const approval = await wallet.writeContract({ account: address, chain, address: usdcAddress, abi: erc20Abi, functionName: 'approve', args: [contractAddress, amount] }); await publicClient.waitForTransactionReceipt({ hash: approval }); }
      setWalletState('Confirm payment in your wallet'); const hash = await wallet.writeContract({ account: address, chain, address: contractAddress, abi: sikaPayAbi, functionName: 'payInvoice', args: [invoice.onchainId, token === 'ETH' ? zeroAddress : usdcAddress, amount], value: token === 'ETH' ? amount : 0n }); setWalletState('Confirming on Sepolia'); const receipt = await publicClient.waitForTransactionReceipt({ hash, confirmations: 1 }); if (receipt.status !== 'success') throw new Error('Transaction reverted'); setWalletState('Verifying payment'); const payment = await confirmPayment({ invoiceReference: invoice.reference, txHash: hash, senderAddress: address, asset: token, cryptoAmount: quote.amountCrypto }); navigate(`/transaction/${payment.transactionId}`);
    } catch (e) { setError(walletError(e)); setWalletState(''); setSubmitting(false); } };
  return <div className="shell py-8"><Link to="/pay" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-forest"><ArrowLeft size={17} />Choose another invoice</Link><div className="mx-auto grid max-w-5xl gap-6 lg:grid-cols-[1fr_.8fr]"><div className="space-y-5"><div className="card p-6 sm:p-8"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-forest text-white"><Store /></span><span className="rounded-full bg-emerald/10 px-3 py-1 text-xs font-bold text-emerald">Secure invoice</span></div><p className="mt-7 text-sm text-[#66766e]">Paying</p><h1 className="mt-1 text-3xl font-extrabold">{invoice.merchantName}</h1><p className="mt-2 text-[#66766e]">{invoice.description}</p><div className="my-6 border-t border-black/5" /><p className="text-sm text-[#66766e]">Amount requested</p><p className="amount mt-1 text-4xl font-extrabold text-forest">{money(invoice.amountGhs)}</p><p className="mt-5 rounded-2xl bg-[#e9f5ed] p-4 text-sm font-semibold leading-6 text-forest">{invoice.merchantName} receives {money(invoice.amountGhs)} through {networkName(invoice.network)}.</p><div className="mt-4 flex justify-between text-xs text-[#718078]"><span>Expires {new Date(invoice.expiresAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><span>{maskPhone(invoice.merchantPhone)}</span></div></div><div className="card p-6"><label className="label">Choose how to pay</label><TokenSelector value={token} onChange={setToken} /></div></div><div className="space-y-5"><PaymentSummaryCard invoice={invoice} token={token} /><div className="card p-6"><ConnectWalletButton /><button onClick={pay} disabled={expired || paid || submitting || wrongNetwork || !isConnected} className="btn-primary mt-3 w-full">{walletState || (expired ? 'Invoice expired' : paid ? 'Already paid' : 'Confirm payment')}</button><p className="mt-4 flex items-center justify-center gap-1.5 text-xs text-[#75837c]"><LockKeyhole size={13} />SikaPay never takes custody of your wallet.</p>{error && <p className="mt-3 flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={17} />{error}</p>}</div></div></div></div>;
}
