import gsap from 'gsap';import {useGSAP} from '@gsap/react';import {useReducedMotion} from 'motion/react';import {useCallback,useEffect,useRef,useState} from 'react';import {Link} from 'react-router-dom';
gsap.registerPlugin(useGSAP);
interface SplashScreenProps{onReveal:()=>void;onDocked:()=>void}
export function SplashScreen({onReveal,onDocked}:SplashScreenProps){const reduced=useReducedMotion(),scope=useRef<HTMLDivElement>(null),brand=useRef<HTMLAnchorElement>(null),overlay=useRef<HTMLDivElement>(null),subtext=useRef<HTMLParagraphElement>(null),[letters,setLetters]=useState(reduced?7:0),docked=useRef(false);
  const positionAtTarget=useCallback(()=>{const target=document.querySelector<HTMLElement>('[data-navbar-brand-target]'),el=brand.current;if(!target||!el)return;const box=target.getBoundingClientRect();gsap.set(el,{x:box.left,y:box.top})},[]);
  useGSAP(()=>{const el=brand.current,target=document.querySelector<HTMLElement>('[data-navbar-brand-target]');if(!el||!target)return;const targetBox=target.getBoundingClientRect();gsap.set(el,{x:(innerWidth-el.offsetWidth)/2,y:(innerHeight-el.offsetHeight)/2,transformOrigin:'top left'});gsap.to('.intro-cursor',{opacity:0,duration:.3,repeat:-1,yoyo:true,ease:'none'});
    if(reduced){setLetters(7);gsap.set('.intro-icon',{width:40,height:40,borderRadius:12});gsap.set('.intro-word',{fontSize:20,minWidth:0,letterSpacing:'-.035em'});gsap.set(el,{x:targetBox.left,y:targetBox.top,gap:8,opacity:1,scale:1});gsap.to(overlay.current,{opacity:0,duration:.18,onStart:onReveal,onComplete:()=>{docked.current=true;onDocked()}});return}
    const entrance=gsap.fromTo(el,{opacity:0,scale:.82,y:`-=${12}`},{opacity:1,scale:1,y:`+=${12}`,duration:.6,ease:'power3.out'});gsap.fromTo(subtext.current,{opacity:0,y:8},{opacity:1,y:0,duration:.4,delay:.48,ease:'power2.out'});
    const typingStart=window.setTimeout(()=>{let next=0;const typing=window.setInterval(()=>{next+=1;setLetters(Math.min(next,7));if(next>=7)clearInterval(typing)},70)},650);
    const dockStart=window.setTimeout(()=>{onReveal();const fresh=target.getBoundingClientRect();gsap.to(subtext.current,{opacity:0,y:-6,duration:.25});gsap.to(overlay.current,{opacity:0,duration:.58,ease:'power2.out'});gsap.to(el,{x:fresh.left,y:fresh.top,gap:8,duration:.72,ease:'power3.inOut'});gsap.to('.intro-icon',{width:40,height:40,borderRadius:12,duration:.72,ease:'power3.inOut'});gsap.to('.intro-word',{fontSize:20,minWidth:0,letterSpacing:'-.035em',duration:.72,ease:'power3.inOut',onComplete:()=>{docked.current=true;onDocked()}})},1450);
    return()=>{entrance.kill();clearTimeout(typingStart);clearTimeout(dockStart)}
  },{scope,dependencies:[onReveal,onDocked,reduced]});
  useEffect(()=>{const resize=()=>docked.current&&positionAtTarget();addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[positionAtTarget]);
  const typed='SikaPay'.slice(0,letters);return <div ref={scope}><div ref={overlay} className="fixed inset-0 z-[100] bg-white"/><p ref={subtext} className="pointer-events-none fixed left-1/2 top-[calc(50%+105px)] z-[112] -translate-x-1/2 whitespace-nowrap text-xs font-semibold tracking-[.16em] text-[#75837c]">GLOBAL CRYPTO · LOCAL PAYMENTS</p><Link ref={brand} to="/" aria-label="SikaPay home" className="fixed left-0 top-0 z-[115] flex items-center gap-4 sm:gap-6"><span className="intro-icon grid h-32 w-32 shrink-0 place-items-center overflow-hidden rounded-[1.75rem] bg-white sm:h-36 sm:w-36"><img src="/assets/logo-only.png" alt="" className="h-full w-full scale-[2.05] object-cover"/></span><span className="intro-word min-w-[180px] text-left font-[Manrope] text-4xl font-semibold tracking-[-.045em] text-forest sm:min-w-[215px] sm:text-5xl" aria-label="SikaPay">{typed.slice(0,4)}<span className="text-emerald">{typed.slice(4)}</span>{letters<7&&<span aria-hidden="true" className="intro-cursor ml-1 inline-block h-[.92em] w-[3px] translate-y-[.08em] bg-emerald"/>}</span></Link></div>}
